#!/usr/bin/env bash

set -eu

usage() {
  cat <<EOF

Usage: kubectl exec-as [OPTIONS] <pod name> [-- <commands...>]

Run a command in a running container

Options:
  -h  Show usage
  -d  Enable debug mode. Print a trace of each commands
  -n  If present, the namespace scope for this CLI request
  -u  Username or UID (format: <name|uid>[:<group|gid>])
  -g  The namespace of distination pod generatored in
  -c  Container name. If omitted, the first container in the pod will be chosen
EOF
  exit 0
}

to_json() {
  text="$*"
  p=""
  for i in $text; do
    [[ -n "$p" ]] && p+=", "
    p+="\"$i"\"
  done
  echo -en "$p"
}

[ $# -eq 0 ] && usage

KUBECTL="$(type -p kubectl)"
COMMAND="/bin/sh"
USERNAME="root"
CONTAINER="NONE"
NAMESPACE="NONE"
GENERATOR="default"

while getopts "hdpg:n:u:c:" arg; do
  case $arg in
    p) # Specify pod name.
      POD=${OPTARG}
      ;;
    g) # generatored pod running namespace, different from given pod's namespace
      GENERATOR=${OPTARG}
      ;;
    n) # Specify namespace
      NAMESPACE=${OPTARG}
      ;;
    u) # Specify user
      USERNAME=${OPTARG}
      ;;
    c) # Specify container
      CONTAINER=${OPTARG}
      ;;
    d) # Enable debug mode
      set -x
      ;;
    h) # Display help.
      usage
      ;;
    \?)
      usage
      ;;
  esac
done

shift $((OPTIND-1))
if [[ -z ${1+x} ]]; then
  echo "Error: You have to specify the pod name" >&2
  usage
fi
POD="$1"
shift

if [[ $# -gt 0 ]]; then
  if [[ $1 == "--" ]]; then
    shift
    COMMAND="$*"
  else
    echo "Error: Invalid option: $0" >&2
    usage
  fi
fi

echo -e "\nConnecting...\nPod: ${POD}\nNamespace: ${NAMESPACE}\nUser: ${USERNAME}\nContainer: ${CONTAINER}\nCommand: ${COMMAND}\n"

container=${NAMESPACE}-${POD}-${USERNAME}

if [[ ${CONTAINER} != "NONE" ]]; then
  DOCKER_CONTAINERID=$( eval "$KUBECTL" -n ${NAMESPACE} get pod "${POD}" -o go-template="'{{ range .status.containerStatuses }}{{ if eq .name \"${CONTAINER}\" }}{{ .containerID }}{{ end }}{{ end }}'" )
else
  DOCKER_CONTAINERID=$( $KUBECTL -n ${NAMESPACE} get pod "${POD}" -o go-template='{{ (index .status.containerStatuses 0).containerID }}' )
fi
CONTAINERID=${DOCKER_CONTAINERID#*//}

trap '$KUBECTL -n ${GENERATOR} delete pod $container' 0 1 2 3 15

if [[ $(${KUBECTL} -n ${GENERATOR} get pod --field-selector=status.phase==Running --no-headers| grep ${container}| wc -l) -eq 1 ]]; then
  # if existing, then exec into it.
  eval "${KUBECTL}" -n ${GENERATOR} exec -it "$container" -- docker exec -it -u ${USERNAME} ${CONTAINERID} $(to_json "${COMMAND}")
else
  # delete first no matter which status existing pod is
  $KUBECTL -n ${GENERATOR} delete pod $container --ignore-not-found
  # by z.s.k, if pod is exist, then reuse it instead of shown pod was existed error(will be deleted by cronjob).
  # wheanwhile, change pod name rule with pod given name by kubectl run and -u(username) args, e.g: username-podname
  # Limits concurrent sessions (each session deploys a pod) to 2. It's not necessary, just a preference.
  # test "$(exec "${KUBECTL}" -n ${GENERATOR} get po "$(whoami|tr -dc '[:alnum:]')-1" 2>/dev/null)" && container="$(whoami|tr -dc '[:alnum:]')-2" || container="$(whoami|tr -dc '[:alnum:]')-1"

  # We want to mount the docker socket on the node of the pod we're exec'ing into.
  NODENAME=$( ${KUBECTL} -n ${NAMESPACE} get pod "${POD}" -o go-template='{{.spec.nodeName}}' )
  NODESELECTOR='"nodeSelector": {"kubernetes.io/hostname": "'$NODENAME'"},'

  # Adds toleration if the target container runs on a tainted node. Assumes no more than one taint. Change if yours have more than one or are configured differently.
  TOLERATION_VALUE=$($KUBECTL -n ${NAMESPACE} get pod "${POD}" -ojsonpath='{.spec.tolerations[].value}') >/dev/null 2>&1
  if [[ "$TOLERATION_VALUE" ]]; then
  TOLERATION_KEY=$($KUBECTL -n ${NAMESPACE} get pod "${POD}" -ojsonpath='{.spec.tolerations[].key}')
  TOLERATION_OPERATOR=$($KUBECTL -n ${NAMESPACE} get pod "${POD}" -ojsonpath='{.spec.tolerations[].operator}')
  TOLERATION_EFFECT=$($KUBECTL -n ${NAMESPACE} get pod "${POD}" -ojsonpath='{.spec.tolerations[].effect}')
  TOLERATIONS='"tolerations": [{"effect": "'$TOLERATION_EFFECT'","key": "'$TOLERATION_KEY'","operator": "'$TOLERATION_OPERATOR'","value": "'$TOLERATION_VALUE'"}],'
  else
      TOLERATIONS=''
  fi

  read -r -d '' OVERRIDES <<EOF || :
{
    "apiVersion": "v1",
    "spec": {
        "containers": [
            {
                "image": "harbor.local.io/k8s/docker:20.10.18",
                "name": "'$container'",
                "stdin": true,
                "stdinOnce": true,
                "tty": true,
                "restartPolicy": "Never",
                "args": [
                  "exec",
                  "-it",
                  "-u",
                  "${USERNAME}",
                  "${CONTAINERID}",
                  $(to_json "${COMMAND}")
                ],
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "docker"
                    }
                ]
            }
        ],

        $NODESELECTOR

        $TOLERATIONS

        "volumes": [
            {
                "name": "docker",
                "hostPath": {
                    "path": "/var/run/docker.sock",
                    "type": ""
                }
            }
        ]
    }
}
EOF

  # by z.s.k, $container is also pod name
  eval "$KUBECTL" -n "${GENERATOR}" run -it --restart=Never --image=harbor.local.io/k8s/docker:20.10.18 --overrides="'${OVERRIDES}'" "$container"
fi